### ISSUE TITLE
Corrupted Traces in Tournament Mode

### ISSUE THREAD

**Issue by FacelessJ** [santiontanon/microrts#27] opened 2018-05-10 08:07 UTC
Trying to view traces generated by tournaments (Both tournaments I've run myself as well as traces from the 2017 competition), in the Traces pane of the FrontEnd GUI causes an error, generally around `t=50` when the first workers are finished and issued commands. Viewing the xml file, it appears actions are being saved with invalid unit IDs. For example, see Line `954` of `7-vs-6-7-3.xml` of the 2017 competition. There is an action for a downward movement for unit `152027043`. This ID does not occur anywhere else in the file.

Running a match with the same settings in tournament mode and the state pane (i.e. 1 iteration, same two (built-in) AI, etc) results in a corrupted trace from the tournament, but a working trace from the state pane.

The `RoundRobinTournament` constructs traces by cloning the player actions, while `FEStatePane` just passes `pa1` and `pa2` rather than cloning. Removing the `clone()` process from `RoundRobinTournament` produces uncorrupted traces.

Although, looking at the cloning code for `PlayerAction`, it's not obvious to me what the root issue is. 

Lastly, corruption happens regardless of whether the GC is run before each AI call.

**Comment by santiontanon** [comment] 2018-05-10 13:50
Thanks for reporting!!! I'll look into this this weekend.

**Comment by santiontanon** [comment] 2018-05-10 14:04
But I just tried very quick, and I can confirm that I can reproduce the crash you report. So, I'll look into it later! Thanks again!

**Comment by santiontanon** [comment] 2018-05-10 21:19
I just committed a fix for this. Unfortunately the traces that were corrupted are hard to repair, since it will be very hard (possible, but hard) to figure out which units those actions with extraneous IDs were issued to. Any trace generated from now on should be fine, but old traces will not be re-playable.

However, that being said, it might be possible to create a "trace fixer" that takes a broken trace and fixes it by iteratively guessing which unit was an action for until the trace is consistent. Let me know if this would be useful/needed, and I will try to find time for it. 

Will close the ticket, but feel free to reopen if this is still an issue :)

**Closed by santiontanon** 2018-05-10 21:19 UTC
